<svelte:head>
	<title>Governance - dyad.</title>
	<meta name="description" content="How dyad is governed: steward ownership, dual voting, and why investors don't run this." />
</svelte:head>

<main class="community-page">
	<a href="/" class="back-link">
		<svg width="16" height="16" viewBox="0 0 20 20" fill="none" style="vertical-align:middle;margin-right:4px"><path d="M12 15l-5-5 5-5" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"/></svg>
		dyad.berlin
	</a>

	<nav class="page-nav">
		<a href="/community" class="nav-link">charter</a>
		<span class="nav-sep">/</span>
		<a href="/community/membership" class="nav-link">membership</a>
		<span class="nav-sep">/</span>
		<a href="/community/criteria" class="nav-link">acceptance</a>
		<span class="nav-sep">/</span>
		<a href="/community/standards" class="nav-link">standards</a>
		<span class="nav-sep">/</span>
		<a href="/community/governance" class="nav-link active">governance</a>
	</nav>

	<h1>Governance</h1>
	<p class="subtitle">Steward ownership, dual voting, and why investors don't run this.</p>

	<section>
		<p class="lede">A platform is not corrupted by bad people. It is corrupted by a structure that makes bad outcomes inevitable. When a company is financed through equity, it is obligated to grow. When growth plateaus, it extracts. When extraction meets resistance, it pivots to the next extractable thing. This is not a story about founders losing their way - it is a story about a structure doing exactly what it was designed to do.</p>
		<p class="lede-secondary">Dyad is built to be different in structure, not just in intention. This document explains that structure: where we are now, what we have committed to, how governance works at every level, and what it will mean for members when the transition to steward ownership is complete.</p>
	</section>

	<section>
		<h2>What this model is trying to achieve</h2>
		<p>Dyad's ownership and governance structure is designed to achieve five things simultaneously - not as aspirations, but as structural properties encoded into the form of the company itself.</p>

		<div class="objectives-list">
			<div class="objective">
				<div class="objective-num">01</div>
				<div>
					<div class="objective-rule">No investor governance, ever.</div>
					<p>People who provide capital have no say in how the platform is run, what it optimises for, or who it can be sold to. This is guaranteed by the steward ownership structure - not by good intentions that can be revised when they become inconvenient.</p>
				</div>
			</div>
			<div class="objective">
				<div class="objective-num">02</div>
				<div>
					<div class="objective-rule">Profit serves purpose, not the reverse.</div>
					<p>Surplus generated by the platform is reinvested into the platform, distributed to workers as reasonable compensation, or used to subsidise the community pricing tier. It is not extracted by investors. Investor returns are capped and defined before capital is received.</p>
				</div>
			</div>
			<div class="objective">
				<div class="objective-num">03</div>
				<div>
					<div class="objective-rule">Community governs community affairs.</div>
					<p>The people who use the platform decide how it is run. Standards, criteria, and policy are set by the People's Assembly - not by the platform's founders or its investors.</p>
				</div>
			</div>
			<div class="objective">
				<div class="objective-num">04</div>
				<div>
					<div class="objective-rule">No sale without community consent.</div>
					<p>After the steward ownership transition, the platform cannot be sold to a party whose interests conflict with its purpose without the consent of the Purpose Foundation anchor. The People's Assembly is in the room when acquisition decisions are made.</p>
				</div>
			</div>
			<div class="objective">
				<div class="objective-num">05</div>
				<div>
					<div class="objective-rule">Sustainable without exploitation.</div>
					<p>The business model is subscription-based. Success is measured by whether members value the platform enough to pay for it - not by time-on-screen, data value, or advertising revenue. No revenue mechanism that conflicts with the community's interests can be introduced.</p>
				</div>
			</div>
		</div>
	</section>

	<section>
		<h2>The structural problem</h2>

		<div class="problem-grid">
			<div class="problem-item">
				<div class="problem-label">Misaligned incentives</div>
				<p>Equity-financed platforms are structurally obligated to prioritise investor returns. When users and investors want different things, investors win. This is not a governance failure - it is the governance working as designed.</p>
			</div>
			<div class="problem-item">
				<div class="problem-label">Governance without accountability</div>
				<p>Platform communities generate enormous value - through their content, their data, their trust, their time. But they have no formal claim on the decisions that affect them. Users are the product, not the owners.</p>
			</div>
			<div class="problem-item">
				<div class="problem-label">Value extraction</div>
				<p>As Cory Doctorow documented: platforms serve users first, then business customers, then extract maximum value from both. Social platforms have moved through this arc faster than most. The community has no structural recourse.</p>
			</div>
			<div class="problem-item">
				<div class="problem-label">Why existing alternatives fall short</div>
				<p>Traditional cooperatives struggle to raise capital. Equity crowdfunding limits ownership to financial contribution. Tokens offer no real governance rights. Profit sharing confers no ownership. The challenge is building something that combines cooperative control with functional financing - without trading one for the other.</p>
			</div>
		</div>
	</section>

	<section>
		<h2>Why existing alternatives fall short</h2>
		<p>If the structural problem is clear, the question is why existing alternatives have not solved it. Understanding the gaps in each model is part of understanding why dyad is built the way it is.</p>

		<h3>Traditional cooperatives</h3>
		<p>Co-ops solve the governance problem by giving members ownership and control. They struggle to solve the capital problem: cooperatives cannot issue equity, which limits their access to external investment. Without access to growth capital, they compete at a structural disadvantage against equity-financed companies in winner-take-most markets. Platforms - where network effects reward the first mover - are a particularly difficult environment for co-op formation.</p>

		<h3>Equity crowdfunding</h3>
		<p>Equity crowdfunding extends ownership to more people - but ownership remains tied to financial contribution. The people who know the platform best (who use it most, who built the trust infrastructure, who depend on it) may own less than investors who contributed capital early. Governance rights track money, not engagement. This is a better distribution than traditional equity, but it reproduces the same fundamental alignment problem: governance stake accumulates to capital, not participation.</p>

		<h3>Tokens and DAOs</h3>
		<p>Token-based governance promised community ownership but largely delivered governance theatre. Most token holders have no meaningful mechanism to exercise governance, and the structures that do exist tend to be captured by large holders who acquired their stakes financially rather than through participation. The novelty of the mechanism obscured how little it changed the underlying dynamics.</p>

		<h3>Profit sharing</h3>
		<p>Distributing returns to workers or users addresses the distribution problem without addressing the control problem. A platform can pay out profits while remaining fully controlled by its equity holders. Profit sharing does not give recipients a voice in how the platform is run, what it optimises for, or who can acquire it. It is better than nothing. It is not governance.</p>

		<p>The challenge is: how do you combine cooperative control - where the people who use and operate the platform govern it - with functional capital access - enough investment to build something that works, without surrendering governance to investors in exchange? Steward ownership is the structure that attempts to solve both simultaneously. It is not a complete solution. It is the best available one, and it requires ongoing design choices to make it real rather than nominal.</p>
	</section>

	<section>
		<h2>Where we are now</h2>
		<p>Dyad is currently raising pre-seed funding. We have made a public commitment to transition to steward ownership, and our funding instrument is designed explicitly to enable that: investors accept from the outset that the company will transition to a steward-owned structure. They do not hold traditional equity. They will have no governance claim after the transition. This is agreed before capital is received - not asked for afterwards.</p>
		<p>We plan to complete the legal transition within approximately eighteen months. But we have set a condition on ourselves: community activation must precede the transition. The legal structure is only worth locking in if the community it is meant to protect is real and functioning. We want to earn that lock-in, not claim it prematurely.</p>
		<p>The People's Assembly described below is being built now - as a real governance body, not a feature placeholder. The community proves itself first. The structural protections follow.</p>
	</section>

	<section>
		<h2>Steward ownership explained</h2>
		<p>In a steward-owned company, voting control stays permanently with the people who operate it. It does not transfer to investors. It cannot be sold to a buyer whose interests conflict with the company's purpose. Profits are not extracted through equity - investors receive capped returns, and their financial claim then ends. They do not accumulate an ongoing share of the company's value. They cannot vote on governance decisions or force a sale.</p>
		<p>The legal structure makes this binding. These are not policies that future leadership can abandon. They are encoded in the corporate form itself, which requires the consent of a purpose-protecting anchor to change. The Purpose Foundation network provides this anchor. Even if every current steward wanted to convert to a traditional equity structure, they could not do so unilaterally.</p>
		<p>Reference companies: Ecosia (search engine, Berlin), Einhorn (consumer goods, Berlin), Waschbär (retail) - all operating under the German <em>Verantwortungseigentum</em> framework, demonstrating the model works at scale without compromising purpose.</p>

		<div class="callout">
			<p>Steward ownership is not a values statement. It is a legal constraint. The distinction matters: values can be revised; legal structures require a structural act to undo. Our commitment is to make these things the same - to encode our values into the structure so that no future change in personnel, leadership, or investor composition can override them.</p>
		</div>
	</section>

	<section>
		<h2>How we are funded</h2>
		<p>Dyad is raising pre-seed capital through a funding instrument designed specifically for companies on the steward ownership path. Our investors enter knowing - and agreeing to - the transition. They do not receive traditional equity. They receive capped returns, no ongoing governance claim, and no veto over operational decisions.</p>
		<p>This means: investors cannot vote on how dyad is run. They cannot force a sale, block a policy decision, or override community governance. Their financial relationship is bounded from the start by the terms of the instrument.</p>
		<p>In practice this means we raise more slowly than a company offering uncapped equity returns. The investors who engage with us do so because they understand the model. That self-selection is a feature, not a limitation - the people funding dyad are people who have thought through what it means.</p>
		<p>We publish a summary of investor relationships and the parameters of the funding instrument in the annual financial report available to all members.</p>
	</section>

	<section>
		<h2>Dual voting</h2>
		<p>Dyad operates two parallel governance tracks. Both exclude investors. Together they constitute the full governance of the platform.</p>

		<div class="voting-grid">
			<div class="voting-track">
				<div class="track-label">Track One</div>
				<div class="track-name">Steward governance</div>
				<p>Corporate structure, financial decisions, major strategic changes, stewardship succession. Voting in this track is held by the stewards - currently the founders, with a defined path to include workers as the team grows.</p>
				<p>Investors have no vote here. This is guaranteed by the legal structure - the corporate form prevents the transfer of steward voting rights to external parties.</p>
				<p>Decisions in this track are communicated to the People's Assembly within 30 days. The Assembly cannot override steward governance decisions, but it can formally request explanations and publicly hold stewards accountable to the charter's commitments.</p>
			</div>

			<div class="voting-track">
				<div class="track-label">Track Two</div>
				<div class="track-name">Community governance - the People's Assembly</div>
				<p>Community standards, acceptance criteria, membership policy, platform features that affect community life, and how all of these evolve. Voting in this track belongs to active members.</p>
				<p>Active membership, for Assembly purposes, means completing at least five meetings on the platform and maintaining recent meeting activity. It is not a one-time threshold - Assembly participation is tied to ongoing engagement.</p>
				<p>Investors have no vote here either. No financial relationship with dyad - as investor or subscriber - confers additional voting weight. One active member, one vote.</p>
			</div>
		</div>

		<p>When a decision has implications for both tracks - a structural platform change affecting both corporate operations and community standards - both tracks have meaningful input. The process for resolving conflicts between them is available in the full governance charter on request.</p>
	</section>

	<section>
		<h2>The People's Assembly</h2>
		<p>The People's Assembly is not appointed by us. It is constituted by any active member who chooses to participate - showing up to the Assembly is itself an act of governance.</p>

		<h3>What the Assembly does</h3>
		<p>Reviews and votes on proposed changes to community standards, acceptance criteria, and the membership agreement. Proposes and votes on new policies. Reviews appeals of governance decisions at the reviewer level. Monitors enforcement patterns for consistency. Holds stewards accountable to the charter's commitments through public record.</p>

		<h3>How it works</h3>
		<p>The Assembly meets in writing, asynchronously, via a structured deliberation space accessible to all active members - not a chat channel. It has proposal workflows, comment periods, and formal votes. Asynchronous format means participation is accessible regardless of schedule. You do not have to attend a meeting at a specific time to have a voice.</p>
		<p>Any active member can submit a proposal. A proposal requires a second before it enters the deliberation period. Standard proposals: 7-day minimum deliberation. Major proposals (standards, criteria, this governance document): 14-day minimum. Standard decisions: simple majority with minimum participation threshold. Major decisions: supermajority (two-thirds) with higher participation threshold.</p>

		<h3>Participation as governance stake</h3>
		<p>The People's Assembly model is designed so that the people with the most experience of the platform have the most say in how it is governed. Voting rights are earned through active participation - completing meetings, engaging with the community - not through financial contribution.</p>
		<p>This is what ownership theorists call a patronage model: instead of governance stake tied to financial contribution, it accumulates through use. In dyad's case, the unit of participation is the meeting. Each meeting you complete deepens your understanding of what the platform actually is - who it serves, how it functions, where it succeeds and fails. The people with the most meetings are the people whose judgment about how the platform should be governed is most grounded in experience of it.</p>
		<p>The threshold for Assembly participation - five completed meetings - distinguishes people who have experienced the platform from people who have only read about it. Your financial contribution (at whatever pricing tier you choose) sustains the platform. Your meeting history is your governance stake. These are kept separate by design. Someone who pays the solidarity rate has the same Assembly vote as someone who pays the community rate. An investor in dyad's pre-seed has no Assembly vote at all, regardless of the size of their investment. Governance tracks participation, not capital - by design, and after the steward ownership transition, by legal constraint.</p>

		<h3>What the Assembly cannot do</h3>
		<p>The Assembly cannot vote to introduce advertising, authorise data sales, or lower the floor protections in the community standards. These are founding commitments that predate the Assembly and are not subject to its revision. After the steward ownership transition, they will be encoded in the legal structure and beyond the reach of any vote.</p>
	</section>

	<section>
		<h2>What we have committed to - and what will be locked</h2>
		<p>The following are founding commitments made now as public obligations. They will be encoded permanently in the legal structure when the steward ownership transition is complete. Until then, they are binding on us as founders and on our investors through the funding instrument.</p>

		<div class="commitment-list">
			<div class="commitment">
				<div class="commitment-rule">No advertising, ever.</div>
				<p>Not now, not under different leadership, not through a subsidiary. The business model cannot include advertising as a revenue mechanism - commitment today, legal constraint after transition.</p>
			</div>
			<div class="commitment">
				<div class="commitment-rule">No sale of member data for commercial purposes.</div>
				<p>Member data cannot be sold to third parties, licensed for commercial use, or used for advertising targeting anywhere - commitment today, legal constraint after transition.</p>
			</div>
			<div class="commitment">
				<div class="commitment-rule">Steward ownership completed and preserved.</div>
				<p>We will complete the transition within eighteen months, conditional on community activation proving the model is working. Once complete, the company cannot revert to traditional equity structure. This is the lock-in we are building toward.</p>
			</div>
			<div class="commitment">
				<div class="commitment-rule">No platform sale to a conflicting acquirer.</div>
				<p>After the steward ownership transition, any acquisition requires consent of the Purpose Foundation anchor and the People's Assembly. The community is in the room when those decisions are made.</p>
			</div>
			<div class="commitment">
				<div class="commitment-rule">Community governance preserved.</div>
				<p>The People's Assembly, once established, cannot be dissolved, suspended, or replaced by an appointed body. Building it now - before the legal transition - is what makes the legal transition meaningful.</p>
			</div>
		</div>
	</section>

	<section>
		<h2>Transparency</h2>
		<p>Annual financial reports: revenue by pricing tier, operating costs, surplus allocation, summary of investor terms. Available to all members.</p>
		<p>Steward governance decisions: communicated to the People's Assembly within 30 days, and to all members when they have direct community implications.</p>
		<p>Full governance charter - including conflict resolution process, stewardship succession plan, and detailed voting thresholds - available to members on request.</p>
		<p>Questions about governance that this document does not answer: <a href="mailto:hello@dyad.berlin">hello@dyad.berlin</a>. Governance questions are logged and answered publicly in the Assembly forum where possible.</p>
	</section>

	<section>
		<h2>About this document</h2>
		<p>This governance document is a living document - it represents our current thinking and will be revised through the People's Assembly as the platform matures. It is not a contract or a guarantee of specific future actions. It is an honest account of the structure we are building and why, written to be held up against what we actually do.</p>
		<p>One honest admission: we are doing something that does not have many working precedents at the scale we are aiming for. Steward-owned community platforms exist, but they are few and early. We do not have a proven template to copy. We have studied the available models - co-operatives, steward-owned companies, community-governed platforms - and made the best structural choices we can. We will be wrong about some things. The things that matter most - no advertising, no investor governance, community control - will be encoded into the legal structure so they cannot be revised by any individual or majority. The rest is a working hypothesis, held accountable by the community it is meant to serve.</p>
		<p>The Assembly can propose changes and vote on them. The constitutional commitments cannot be removed by Assembly vote - they require changes to the legal structure itself, which the steward ownership framework makes deliberately difficult. Even stewards cannot rewrite the governance framework that defines their own authority unilaterally - their proposals go through the same Assembly process.</p>
	</section>

	<section class="doc-meta">
		<p>Adopted May 2026 - Version 1.0 - Working draft</p>
		<p>Full governance charter on request: <a href="mailto:hello@dyad.berlin">hello@dyad.berlin</a></p>
		<p>Purpose Foundation: <a href="https://purpose-economy.org" target="_blank" rel="noopener noreferrer">purpose-economy.org</a></p>
	</section>
</main>

<style>
	:global(body) { overflow: auto !important; }

	.community-page {
		max-width: var(--content-standard);
		margin: 0 auto;
		padding: 80px var(--space-6) 120px;
		font-size: var(--text-lg);
		line-height: var(--leading-relaxed);
		color: var(--text-secondary);
	}

	.back-link {
		display: inline-block;
		margin-bottom: var(--space-8);
		font-size: var(--text-base);
		color: var(--text-muted);
		text-decoration: none;
		transition: color 0.2s;
	}
	.back-link:hover { color: var(--text-primary); }

	.page-nav {
		display: flex;
		flex-wrap: wrap;
		align-items: center;
		gap: var(--space-2);
		margin-bottom: 48px;
		font-family: var(--font-mono);
		font-size: var(--text-xs);
		letter-spacing: 0.05em;
	}
	.nav-link { color: var(--text-muted); text-decoration: none; transition: color 0.2s; }
	.nav-link:hover { color: var(--text-primary); }
	.nav-link.active { color: var(--text-primary); }
	.nav-sep { color: var(--border-link); }

	h1 { font-size: var(--text-3xl); font-weight: normal; color: var(--text-primary); margin: 0 0 var(--space-2); }
	.subtitle { font-size: var(--text-base); color: var(--text-muted); margin: 0 0 56px; font-style: italic; }
	.lede { font-size: var(--text-xl); line-height: var(--leading-relaxed); color: var(--text-primary); margin: 0 0 var(--space-5); }
	.lede-secondary { font-size: var(--text-lg); line-height: var(--leading-relaxed); color: var(--text-secondary); margin: 0 0 var(--space-4); }

	section { margin-bottom: var(--space-10); }

	h2 {
		font-size: var(--text-xl);
		font-weight: 500;
		color: var(--text-primary);
		margin: 0 0 var(--space-4);
		padding-top: var(--space-8);
		border-top: 1px solid var(--border-link);
	}

	h3 { font-size: var(--text-lg); font-weight: 500; color: var(--text-primary); margin: var(--space-6) 0 var(--space-2); }
	p { margin: 0 0 var(--space-4); }
	em { font-style: italic; }
	a { color: var(--text-secondary); text-decoration: underline; text-underline-offset: 2px; }
	a:hover { color: var(--text-primary); }

	/* Model objectives */
	.objectives-list {
		display: flex;
		flex-direction: column;
		margin: var(--space-5) 0;
		border: 1px solid var(--border-link);
		border-radius: var(--radius-card);
		overflow: hidden;
	}
	.objective {
		display: flex;
		gap: var(--space-5);
		padding: var(--space-5) var(--space-6);
		border-bottom: 1px solid var(--border-link);
	}
	.objective:last-child { border-bottom: none; }
	.objective-num {
		font-family: var(--font-mono);
		font-size: var(--text-sm);
		color: var(--text-muted);
		flex-shrink: 0;
		width: 24px;
		padding-top: 3px;
	}
	.objective-rule { font-size: var(--text-base); font-weight: 500; color: var(--text-primary); margin-bottom: var(--space-2); }
	.objective p { font-size: var(--text-base); line-height: var(--leading-relaxed); color: var(--text-secondary); margin: 0; }

	/* Problem grid */
	.problem-grid {
		display: grid;
		grid-template-columns: 1fr 1fr;
		gap: var(--space-4);
		margin: var(--space-5) 0;
	}
	.problem-item {
		padding: var(--space-5);
		border: 1px solid var(--border-link);
		border-radius: var(--radius-card);
	}
	.problem-label {
		font-family: var(--font-mono);
		font-size: var(--text-xs);
		letter-spacing: 0.06em;
		color: var(--text-muted);
		text-transform: uppercase;
		margin-bottom: var(--space-3);
	}
	.problem-item p { font-size: var(--text-base); line-height: var(--leading-relaxed); color: var(--text-secondary); margin: 0; }

	/* Callout */
	.callout {
		margin: var(--space-6) 0;
		padding: var(--space-5) var(--space-6);
		border-left: 3px solid var(--text-primary);
		background: var(--bg-control);
		border-radius: 0 var(--radius-card) var(--radius-card) 0;
	}
	.callout p { font-size: var(--text-base); line-height: var(--leading-relaxed); color: var(--text-primary); margin: 0; font-style: italic; }

	/* Voting grid */
	.voting-grid {
		display: grid;
		grid-template-columns: 1fr 1fr;
		gap: var(--space-4);
		margin: var(--space-5) 0 var(--space-6);
	}
	.voting-track {
		padding: var(--space-6);
		border: 1px solid var(--border-link);
		border-radius: var(--radius-card);
	}
	.track-label { font-family: var(--font-mono); font-size: var(--text-xs); letter-spacing: 0.08em; color: var(--text-muted); text-transform: uppercase; margin-bottom: var(--space-2); }
	.track-name { font-size: var(--text-lg); font-weight: 500; color: var(--text-primary); margin-bottom: var(--space-4); }
	.voting-track p { font-size: var(--text-base); line-height: var(--leading-relaxed); color: var(--text-secondary); }

	/* Constitutional commitments */
	.commitment-list {
		display: flex;
		flex-direction: column;
		margin: var(--space-5) 0;
		border: 1px solid var(--border-link);
		border-radius: var(--radius-card);
		overflow: hidden;
	}
	.commitment { padding: var(--space-5) var(--space-6); border-bottom: 1px solid var(--border-link); }
	.commitment:last-child { border-bottom: none; }
	.commitment-rule { font-size: var(--text-base); font-weight: 500; color: var(--text-primary); margin-bottom: var(--space-2); }
	.commitment p { font-size: var(--text-base); line-height: var(--leading-relaxed); color: var(--text-secondary); margin: 0; }

	.doc-meta { margin-top: 64px; padding-top: var(--space-6); border-top: 1px solid var(--border-link); font-size: var(--text-sm); color: var(--text-muted); }
	.doc-meta p { margin: 0 0 var(--space-2); }

	@media (max-width: 680px) {
		.community-page { padding: 48px var(--space-4) 80px; }
		.problem-grid, .voting-grid { grid-template-columns: 1fr; }
		.page-nav { gap: var(--space-1); }
	}
</style>
