#!/usr/bin/env bash
#
# test-env.sh — generate .env.local for local integration/E2E tests.
#
# Reads the currently-running local Supabase instance's config via
# `npx supabase status -o env` and writes the resulting keys into
# .env.local (gitignored). Idempotent — re-running overwrites cleanly.
#
# Usage:
#   npm run db:env            # via package.json
#   bash scripts/test-env.sh
#
# Exits non-zero if:
#   - Supabase is not running (no Docker containers / API port unreachable)
#   - supabase CLI isn't available
#
# .env.local is gitignored by the root .gitignore. Do not remove that.

set -euo pipefail

ENV_FILE=".env.local"

# Check the CLI is installed (via npx — `supabase` dev dep is in package.json)
if ! command -v npx >/dev/null 2>&1; then
	echo "error: npx not found. Install Node 20+." >&2
	exit 1
fi

# Pull the env block. If Supabase isn't running, the CLI exits non-zero with
# a helpful message about running `supabase start` — let that surface.
if ! ENV_OUTPUT=$(npx supabase status -o env 2>&1); then
	echo "error: local Supabase is not running." >&2
	echo "       Start it with:  npm run setup" >&2
	echo "       Or directly:     npx supabase start" >&2
	echo "" >&2
	echo "CLI output:" >&2
	echo "$ENV_OUTPUT" >&2
	exit 1
fi

# supabase status -o env prints lines like:
#   API_URL="http://127.0.0.1:54321"
#   ANON_KEY="eyJ..."
#   SERVICE_ROLE_KEY="eyJ..."
# We remap ANON_KEY → PUBLIC_SUPABASE_ANON_KEY etc. to match the app's env
# variable names.

# `supabase status -o env` can emit non-assignment lines alongside the keys —
# e.g. a leading "Stopped services: [...]" line when optional services
# (imgproxy, edge runtime, pooler) aren't up, or a CLI update banner. Eval only
# the KEY="value" assignment lines so those don't get run as bogus commands
# (which previously failed the whole script with `Stopped: command not found`).
ENV_ASSIGNMENTS=$(printf '%s\n' "$ENV_OUTPUT" | grep -E '^[A-Za-z_][A-Za-z0-9_]*=' || true)
# shellcheck disable=SC2086
eval "$ENV_ASSIGNMENTS"

if [ -z "${API_URL:-}" ] || [ -z "${ANON_KEY:-}" ] || [ -z "${SERVICE_ROLE_KEY:-}" ]; then
	echo "error: supabase status -o env did not return expected keys." >&2
	echo "Raw output was:" >&2
	echo "$ENV_OUTPUT" >&2
	exit 1
fi

cat > "$ENV_FILE" <<EOF
# Generated by scripts/test-env.sh — do not edit by hand.
# Regenerate with:  npm run db:env
#
# These values are pulled from the running local Supabase instance via
# \`npx supabase status -o env\`. They are safe to keep on-disk only
# because they are local-only JWT keys; the file is gitignored.

PUBLIC_SUPABASE_URL=${API_URL}
PUBLIC_SUPABASE_ANON_KEY=${ANON_KEY}
SUPABASE_SERVICE_ROLE_KEY=${SERVICE_ROLE_KEY}
EOF

echo "wrote $ENV_FILE ($(wc -l < "$ENV_FILE") lines)"
echo "  PUBLIC_SUPABASE_URL=$API_URL"
echo "  PUBLIC_SUPABASE_ANON_KEY=${ANON_KEY:0:20}...${ANON_KEY: -6}"
echo "  SUPABASE_SERVICE_ROLE_KEY=${SERVICE_ROLE_KEY:0:20}...${SERVICE_ROLE_KEY: -6}"
